# Generated by Django 5.2.3 on 2026-09-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authention', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authention',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
