# Generated by Django 5.2.3 on 2026-09-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Investors', '0004_alter_investors_id'),
        ('Orders', '0004_orders_total_price_per_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders_investors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested', models.BooleanField(default=False)),
                ('invester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Investors.investors')),
                ('number_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orders')),
            ],
        ),
    ]
