# Generated by Django 5.2.3 on 2026-09-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderInvestors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_investors',
            old_name='number_order',
            new_name='orders',
        ),
    ]
