# Generated by Django 5.2.3 on 2026-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderInvestors', '0002_rename_number_order_orders_investors_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_investors',
            name='CustomsTotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders_investors',
            name='invester_counted',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
