# Generated by Django 5.2.3 on 2026-09-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderInvestors', '0003_orders_investors_customstotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_investors',
            name='profit_for_invester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
