# Generated by Django 6.1.1 on 2026-09-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investors',
            name='InvestorsUser',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='investors',
            name='Withdrawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investors',
            name='profits',
            field=models.IntegerField(default=0),
        ),
    ]
