# Generated by Django 6.1.1 on 2026-09-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0002_alter_investors_investorsuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investors',
            name='Customs',
            field=models.IntegerField(default=0),
        ),
    ]
