# Generated by Django 5.2.3 on 2026-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.IntegerField()),
                ('order_data', models.DateField()),
                ('Customer_name', models.CharField()),
                ('selling_price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('order_size', models.IntegerField()),
                ('price_per_km', models.IntegerField()),
                ('total_delivery_price', models.IntegerField()),
                ('net_profit', models.IntegerField()),
                ('total_profit', models.IntegerField()),
            ],
        ),
    ]
