# Generated by Django 5.2.3 on 2026-09-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total_profit',
            new_name='order_total',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_deposit',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_price',
            field=models.IntegerField(default=0),
        ),
    ]
