# Generated by Django 5.2.3 on 2026-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_rename_total_profit_orders_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer_deposit',
            field=models.IntegerField(),
        ),
    ]
