# Generated by Django 5.2.3 on 2026-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_orders_customer_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_price_per_kg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
